import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../features/navbar/navbar";
import { jwtVerify } from "jose";
import { getJwtSecretKey } from "@/lib/auth";
import { cookies } from "next/headers";

interface UserJwtPayload {
  jti: string;
  sub: string;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("jwtToken")?.value;

  var name = "";

  if (token) {
    const verified = await jwtVerify(
      token,
      new TextEncoder().encode(getJwtSecretKey()),
    );
    console.log("VERIFIED", verified);
    name = (verified.payload as UserJwtPayload).sub || "";
  }

  return (
    <html lang="en">
      <body>
        <Navbar userName={name} />
        {children}
      </body>
    </html>
  );
}
