import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../features/navbar/navbar";
import { jwtVerify } from "jose";
import { getJwtSecretKey } from "@/lib/auth";
import { cookies } from "next/headers";
import ErrorBoundary from "@/helpers/ErrorHandler";

interface UserJwtPayload {
  jti: string;
  sub: string;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let name = "";

  try {
    const cookieStore = cookies();
    const token = cookieStore.get("jwtToken")?.value;

    if (token) {
      const verified = await jwtVerify(
        token,
        new TextEncoder().encode(getJwtSecretKey()),
      );
      name = (verified.payload as UserJwtPayload).sub || "";
    }
  } catch (error) {
    console.error("Error verifying JWT in layout:", error);
  }

  return (
    <html lang="en">
      <body>
        <ErrorBoundary>
          <Navbar userName={name} />
          {children}
        </ErrorBoundary>
      </body>
    </html>
  );
}
